In [3]:
# library 

import pandas as pd

In [10]:
# load csv dalam data frame
df = pd.read_csv('data.csv')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181420 entries, 0 to 181419
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   camera_id            181420 non-null  object
 1   object               181420 non-null  object
 2   track_id             181420 non-null  int64
 3   detection_timestamp  181420 non-null  object
 4   timestamp            181420 non-null  object
 5   location             179579 non-null  object
dtypes: int64(1), object(5)
memory usage: 8.3+ MB

In [13]:
df.head(50)

,camera_id,object,track_id,detection_timestamp,timestamp,location
0,cam1,mobil,9,58200-10-31T06:46:40.000000Z,2026-03-25T14:20:35.432478Z,NaN
1,cam1,mobil,22,58200-10-31T07:20:00.000000Z,2026-03-25T14:20:37.808817Z,NaN
2,cam1,motor,30,58200-10-31T07:53:20.000000Z,2026-03-25T14:20:39.260072Z,NaN
3,cam1,mobil,32,58200-10-31T07:53:20.000000Z,2026-03-25T14:20:39.260218Z,NaN
4,cam1,mobil,34,58200-10-31T08:26:40.000000Z,2026-03-25T14:20:41.420135Z,NaN
5,cam1,mobil,44,58200-10-31T10:06:40.000000Z,2026-03-25T14:20:47.503820Z,NaN
6,cam1,mobil,45,58200-10-31T10:06:40.000000Z,2026-03-25T14:20:47.503949Z,NaN
7,cam1,motor,49,58200-10-31T10:56:40.000000Z,2026-03-25T14:20:50.416803Z,NaN
8,cam1,motor,53,58200-10-31T12:36:40.000000Z,2026-03-25T14:20:56.789388Z,NaN
9,cam1,mobil,56,58200-10-31T13:43:20.000000Z,2026-03-25T14:21:00.072406Z,NaN
10,cam1,mobil,59,58200-10-31T14:00:00.000000Z,2026-03-25T14:21:01.708290Z,NaN
11,cam1,mobil,60,58200-10-31T14:16:40.000000Z,2026-03-25T14:21:02.790374Z,NaN
12,cam1,mobil,61,58200-10-31T14:50:00.000000Z,2026-03-25T14:21:04.268080Z,NaN
13,cam1,mobil,63,58200-10-31T14:50:00.000000Z,2026-03-25T14:21:04.268186Z,NaN
14,cam1,mobil,64,58200-10-31T14:50:00.000000Z,2026-03-25T14:21:04.268244Z,NaN
15,cam1,mobil,67,58200-10-31T15:23:20.000000Z,2026-03-25T14:21:06.335495Z,NaN
16,cam1,mobil,71,58200-10-31T15:56:40.000000Z,2026-03-25T14:21:08.400454Z,NaN
17,cam1,mobil,72,58200-10-31T15:56:40.000000Z,2026-03-25T14:21:08.400548Z,NaN
18,cam1,mobil,74,58200-10-31T17:03:20.000000Z,2026-03-25T14:21:11.894530Z,NaN
19,cam1,mobil,75,58200-10-31T18:10:00.000000Z,2026-03-25T14:21:16.532716Z,NaN
20,cam1,mobil,77,58200-10-31T18:10:00.000000Z,2026-03-25T14:21:16.532869Z,NaN
21,cam1,mobil,83,58200-10-31T18:10:00.000000Z,2026-03-25T14:21:16.532915Z,NaN
22,cam1,mobil,85,58200-10-31T18:43:20.000000Z,2026-03-25T14:21:17.972060Z,NaN
23,cam1,mobil,92,58200-10-31T19:00:00.000000Z,2026-03-25T14:21:19.290845Z,NaN
24,cam1,mobil,99,58200-10-31T19:16:40.000000Z,2026-03-25T14:21:21.141352Z,NaN
25,cam1,mobil,101,58200-10-31T19:33:20.000000Z,2026-03-25T14:21:21.141473Z,NaN
26,cam1,mobil,107,58200-10-31T19:50:00.000000Z,2026-03-25T14:21:22.460406Z,NaN
27,cam1,mobil,82,58200-10-31T20:23:20.000000Z,2026-03-25T14:21:24.651739Z,NaN
28,cam1,mobil,113,58200-10-31T20:23:20.000000Z,2026-03-25T14:21:24.651926Z,NaN
29,cam1,mobil,117,58200-10-31T20:56:40.000000Z,2026-03-25T14:21:26.576683Z,NaN
30,cam1,mobil,120,58200-10-31T20:56:40.000000Z,2026-03-25T14:21:26.576796Z,NaN
31,cam1,mobil,137,58200-10-31T21:46:40.000000Z,2026-03-25T14:21:29.785731Z,NaN
32,cam1,mobil,135,58200-10-31T21:46:40.000000Z,2026-03-25T14:21:29.785963Z,NaN
33,cam1,mobil,148,58200-10-31T22:20:00.000000Z,2026-03-25T14:21:31.985767Z,NaN
34,cam1,mobil,150,58200-10-31T22:36:40.000000Z,2026-03-25T14:21:31.985899Z,NaN
35,cam1,mobil,164,58200-10-31T23:10:00.000000Z,2026-03-25T14:21:34.502763Z,NaN
36,cam1,mobil,166,58200-10-31T23:10:00.000000Z,2026-03-25T14:21:34.502863Z,NaN
37,cam1,mobil,171,58200-10-31T23:43:20.000000Z,2026-03-25T14:21:36.768316Z,NaN
38,cam1,mobil,175,58200-10-31T23:43:20.000000Z,2026-03-25T14:21:36.768425Z,NaN
39,cam1,mobil,183,58200-11-01T00:16:40.000000Z,2026-03-25T14:21:39.691590Z,NaN
40,cam1,mobil,194,58200-11-01T00:33:20.000000Z,2026-03-25T14:21:39.691727Z,NaN
41,cam1,mobil,195,58200-11-01T00:33:20.000000Z,2026-03-25T14:21:39.691784Z,NaN
42,cam1,mobil,160,58200-11-01T00:33:20.000000Z,2026-03-25T14:21:39.691846Z,NaN
43,cam1,mobil,200,58200-11-01T01:06:40.000000Z,2026-03-25T14:21:40.866777Z,NaN
44,cam1,mobil,207,58200-11-01T02:46:40.000000Z,2026-03-25T14:21:47.897566Z,NaN
45,cam1,mobil,210,58200-11-01T03:03:20.000000Z,2026-03-25T14:21:47.897745Z,NaN
46,cam1,mobil,211,58200-11-01T03:20:00.000000Z,2026-03-25T14:21:50.683770Z,NaN
47,cam1,mobil,213,58200-11-01T03:36:40.000000Z,2026-03-25T14:21:50.683897Z,NaN
48,cam1,mobil,214,58200-11-01T03:36:40.000000Z,2026-03-25T14:21:50.683959Z,NaN
49,cam1,mobil,217,58200-11-01T04:10:00.000000Z,2026-03-25T14:21:53.292205Z,NaN

In [14]:
# ganti semua data ke string

df['detection_timestamp'] = df['detection_timestamp'].astype(str)

In [16]:
# ganti value dari 58200 jadi 2026
df['detection_timestamp'] = df['detection_timestamp'].str.replace('58200', '2026')

In [18]:
df.head(10)

,camera_id,object,track_id,detection_timestamp,timestamp,location
0,cam1,mobil,9,2026-10-31T06:46:40.000000Z,2026-03-25T14:20:35.432478Z,NaN
1,cam1,mobil,22,2026-10-31T07:20:00.000000Z,2026-03-25T14:20:37.808817Z,NaN
2,cam1,motor,30,2026-10-31T07:53:20.000000Z,2026-03-25T14:20:39.260072Z,NaN
3,cam1,mobil,32,2026-10-31T07:53:20.000000Z,2026-03-25T14:20:39.260218Z,NaN
4,cam1,mobil,34,2026-10-31T08:26:40.000000Z,2026-03-25T14:20:41.420135Z,NaN
5,cam1,mobil,44,2026-10-31T10:06:40.000000Z,2026-03-25T14:20:47.503820Z,NaN
6,cam1,mobil,45,2026-10-31T10:06:40.000000Z,2026-03-25T14:20:47.503949Z,NaN
7,cam1,motor,49,2026-10-31T10:56:40.000000Z,2026-03-25T14:20:50.416803Z,NaN
8,cam1,motor,53,2026-10-31T12:36:40.000000Z,2026-03-25T14:20:56.789388Z,NaN
9,cam1,mobil,56,2026-10-31T13:43:20.000000Z,2026-03-25T14:21:00.072406Z,NaN

In [20]:
# Konversi 'timestamp' ke datetime terlebih dahulu (ini tanggal yang valid)
df['timestamp'] = pd.to_datetime(df['timestamp'], format='ISO8601')

In [21]:
# Ambil TANGGAL dari 'timestamp' (Jadikan string dengan format YYYY-MM-DD)
tanggal_benar = df['timestamp'].dt.strftime('%Y-%m-%d')

In [22]:
waktu_benar = df['detection_timestamp'].astype(str).str.split('T').str[1]

In [23]:
df['detection_timestamp'] = pd.to_datetime(tanggal_benar + 'T' + waktu_benar, format='ISO8601')

In [24]:
df['detection_timestamp'] = df['detection_timestamp'].dt.tz_convert('Asia/Jakarta')
df['timestamp'] = df['timestamp'].dt.tz_convert('Asia/Jakarta')

In [25]:
df['detection_timestamp'] = df['detection_timestamp'].dt.tz_localize(None)
df['timestamp'] = df['timestamp'].dt.tz_localize(None)

In [26]:
print(df[['detection_timestamp', 'timestamp']].head())

  detection_timestamp                  timestamp
0 2026-03-25 13:46:40 2026-03-25 21:20:35.432478
1 2026-03-25 14:20:00 2026-03-25 21:20:37.808817
2 2026-03-25 14:53:20 2026-03-25 21:20:39.260072
3 2026-03-25 14:53:20 2026-03-25 21:20:39.260218
4 2026-03-25 15:26:40 2026-03-25 21:20:41.420135

In [27]:
df.head(10)

,camera_id,object,track_id,detection_timestamp,timestamp,location
0,cam1,mobil,9,2026-03-25 13:46:40,2026-03-25 21:20:35.432478,NaN
1,cam1,mobil,22,2026-03-25 14:20:00,2026-03-25 21:20:37.808817,NaN
2,cam1,motor,30,2026-03-25 14:53:20,2026-03-25 21:20:39.260072,NaN
3,cam1,mobil,32,2026-03-25 14:53:20,2026-03-25 21:20:39.260218,NaN
4,cam1,mobil,34,2026-03-25 15:26:40,2026-03-25 21:20:41.420135,NaN
5,cam1,mobil,44,2026-03-25 17:06:40,2026-03-25 21:20:47.503820,NaN
6,cam1,mobil,45,2026-03-25 17:06:40,2026-03-25 21:20:47.503949,NaN
7,cam1,motor,49,2026-03-25 17:56:40,2026-03-25 21:20:50.416803,NaN
8,cam1,motor,53,2026-03-25 19:36:40,2026-03-25 21:20:56.789388,NaN
9,cam1,mobil,56,2026-03-25 20:43:20,2026-03-25 21:21:00.072406,NaN

In [28]:
df['location'] = df['location'].fillna('demangan')

In [34]:
df.head(10)

,camera_id,object,track_id,detection_timestamp,timestamp,location
0,cam1,mobil,9,2026-03-25 13:46:40,2026-03-25 21:20:35.432478,demangan
1,cam1,mobil,22,2026-03-25 14:20:00,2026-03-25 21:20:37.808817,demangan
2,cam1,motor,30,2026-03-25 14:53:20,2026-03-25 21:20:39.260072,demangan
3,cam1,mobil,32,2026-03-25 14:53:20,2026-03-25 21:20:39.260218,demangan
4,cam1,mobil,34,2026-03-25 15:26:40,2026-03-25 21:20:41.420135,demangan
5,cam1,mobil,44,2026-03-25 17:06:40,2026-03-25 21:20:47.503820,demangan
6,cam1,mobil,45,2026-03-25 17:06:40,2026-03-25 21:20:47.503949,demangan
7,cam1,motor,49,2026-03-25 17:56:40,2026-03-25 21:20:50.416803,demangan
8,cam1,motor,53,2026-03-25 19:36:40,2026-03-25 21:20:56.789388,demangan
9,cam1,mobil,56,2026-03-25 20:43:20,2026-03-25 21:21:00.072406,demangan

In [35]:
# Kita hitung jumlah track_id yang unik (nunique)
df_harian = df.resample('D', on='detection_timestamp')['track_id'].nunique().reset_index()

In [36]:
# 2. Rapikan nama kolomnya agar enak dibaca
df_harian.columns = ['Tanggal', 'Total_Kendaraan']

In [37]:
# 3. Urutkan data dari yang paling banyak ke paling sedikit (Descending)
df_harian_tertinggi = df_harian.sort_values(by='Total_Kendaraan', ascending=False)

In [38]:
# 4. Tampilkan hasilnya (misal 5 hari paling ramai)
print("--- 5 Hari dengan Volume Kendaraan Tertinggi ---")
print(df_harian_tertinggi.head())

--- 5 Hari dengan Volume Kendaraan Tertinggi ---
     Tanggal  Total_Kendaraan
4 2026-03-29            71286
5 2026-03-30            57796
6 2026-03-31            15265
3 2026-03-28             3788
0 2026-03-25             1222

In [39]:
df_puncak = df[df['detection_timestamp'].dt.strftime('%Y-%m-%d') == '2026-03-29']

In [40]:
print(f"Total baris data di tanggal 29 Maret: {len(df_puncak)}")
df_puncak.head()

Total baris data di tanggal 29 Maret: 85552

,camera_id,object,track_id,detection_timestamp,timestamp,location
2156,cam1,mobil,62,2026-03-29 00:03:20,2026-03-29 05:40:23,demangan
2157,cam3,mobil,157,2026-03-29 00:03:20,2026-03-29 05:40:23,yos_sudarso
2158,cam3,motor,166,2026-03-29 00:03:20,2026-03-29 05:40:23,yos_sudarso
2159,cam3,mobil,171,2026-03-29 00:03:20,2026-03-29 05:40:23,yos_sudarso
2160,cam3,motor,177,2026-03-29 00:53:20,2026-03-29 05:40:26,yos_sudarso

In [42]:
# Kelompokkan data df_puncak per jam ('H')
df_puncak_per_jam = df_puncak.resample('h', on='detection_timestamp')['track_id'].nunique().reset_index()
df_puncak_per_jam.columns = ['Waktu', 'Volume_Kendaraan']

In [43]:
# Tampilkan 5 jam paling sibuk di hari itu
jam_sibuk = df_puncak_per_jam.sort_values(by='Volume_Kendaraan', ascending=False)
print("--- Jam Paling Sibuk di Tanggal 29 Maret 2026 ---")
print(jam_sibuk.head())

--- Jam Paling Sibuk di Tanggal 29 Maret 2026 ---
                 Waktu  Volume_Kendaraan
22 2026-03-29 22:00:00              5017
9  2026-03-29 09:00:00              5010
8  2026-03-29 08:00:00              5007
20 2026-03-29 20:00:00              4991
21 2026-03-29 21:00:00              4982

In [44]:
# Menghitung jenis kendaraan khusus di hari itu
komposisi_kendaraan = df_puncak.groupby('object')['track_id'].nunique().sort_values(ascending=False).reset_index()
print("\n--- Komposisi Kendaraan ---")
print(komposisi_kendaraan)

--- Komposisi Kendaraan ---
     object  track_id
0     mobil     45744
1     motor     30079
2  bus_truk      1208
3    sepeda       923

In [45]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181420 entries, 0 to 181419
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   camera_id            181420 non-null  object
 1   object               181420 non-null  object
 2   track_id             181420 non-null  int64
 3   detection_timestamp  181420 non-null  datetime64[ns]
 4   timestamp            181420 non-null  datetime64[ns]
 5   location             181420 non-null  object
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 8.3+ MB
None

In [46]:
print(df.isna().sum())

camera_id              0
object                 0
track_id               0
detection_timestamp    0
timestamp              0
location               0
dtype: int64

In [47]:
jumlah_duplikat = df.duplicated().sum()
print(f"Jumlah baris duplikat persis: {jumlah_duplikat}")

Jumlah baris duplikat persis: 0

In [48]:
print("Waktu paling awal  :", df['detection_timestamp'].min())
print("Waktu paling akhir :", df['detection_timestamp'].max())

Waktu paling awal  : 2026-03-25 07:00:00
Waktu paling akhir : 2026-03-31 06:56:40

In [50]:
df.to_csv('data_cctv_clean_v1.csv', index=False)